name: Deploy Environment

on: 
    workflow_call:
        inputs:
            environment:
                required: true
                type: string


jobs:
    env_deploy:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
            - name: Mostrar variables del entorno seleccionado
              run:
                echo "API_LEVEL:" ${{ vars.API_URL }}
                echo "LOG_LEVEL:" ${{ vars.LOG_LEVEL }}