name: Deploy Environment

on: 
    workflow_call:
        inputs:
            environment:
                required: true
                type: string


jobs:
    env_deploy:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
            - name: Mostrar entorno usado para realizar el despliegue
              run: |
                echo "El entorno seleccionado para el despliegue ha sido:" ${{ inputs.environment }}